In [1]:
%load_ext autoreload
%autoreload 2

In [129]:
import tensorflow as tf
import numpy as np

In [130]:
from eventcnn.datasources.davis import DavisDataset
from eventcnn.datasources.eventsource import EventSource

In [131]:
dataset1 = DavisDataset.named_dataset("poster_translation")
dataset2 = DavisDataset.named_dataset("shapes_translation")

In [132]:
source1 = EventSource(dataset1, 
                      testing_fraction=0.2,
                      validation_fraction=0.4,
                      events_per_block=1000)
source2 = EventSource(dataset2, 
                      testing_fraction=0.2,
                      validation_fraction=0.4,
                      events_per_block=1000)

In [133]:
source2.write_records("records", n_layers=4, scaling=2)

training 1
training 2
training 3
training 4
training 5
training 6
training 7
training 8
training 9
training 10
training 11
training 12
training 13
training 14
training 15
training 16
training 17
training 18
training 19
training 20
training 21
validation 1
validation 2
validation 3
validation 4
validation 5
validation 6
validation 7
validation 8
validation 9
validation 10
validation 11
validation 12
validation 13
validation 14
validation 15
validation 16
validation 17
validation 18
validation 19
validation 20
validation 21
testing 1
testing 2
testing 3
testing 4
testing 5
testing 6
testing 7
testing 8
testing 9
testing 10
testing 11
testing 12
testing 13
testing 14
testing 15
testing 16
testing 17
testing 18
testing 19
testing 20
testing 21


In [76]:
source1.num_training / 60 / 60

11.083333333333334

In [94]:
z = np.zeros((3,4))
z

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [95]:
indices = np.array([[0, 1], [2, 0]])

In [100]:
flat_indices = np.ravel_multi_index(indices.T, z.shape)

In [101]:
flat_indices

array([1, 8])

In [ ]:
z

In [88]:
z.flat[np.array([0, 2, 4])] = 1
z

array([[ 1.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [83]:
z[np.array([[0, 1], [2, 2]]).T] = 1
z

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [89]:
np.cumprod?

In [84]:
np.index_exp?

In [85]:
np.indices?

In [60]:
z.flatten?

In [134]:
import array

In [139]:
x = np.zeros(3, dtype=int)
a = array.array('b', x)

In [140]:
a[0] = 1

In [142]:
a

array('b', [1, 0, 0])

In [136]:
array.array?

In [48]:
np.zeros(3).astype(int).tolist()

[0, 0, 0]

In [49]:
tf.train.Int64List(value=np.zeros(3).astype(int).tolist())

value: 0
value: 0
value: 0